[package]
name = "psyk"
version = "0.1.0"
authors = ["Michael Shaw <michaeljshaw@gmail.com>"]

[dependencies]
fnv = "1.0"
serde = "0.9"
serde_json = "0.9"
serde_derive = "0.9"
tokio-core = "0.1"
tokio-io = "0.1"
futures = "0.1"
bytes = "0.4"